server:
  port: 8081

abtest:
  enabled: true
  sync-mode: websocket
  service-code: service_help_1
  server-url: ws://localhost:8080
  websocket:
    path: "/ws/config"              # WebSocket路径
    reconnect-interval-seconds: 5   # 重连间隔
    max-reconnect-attempts: 10      # 最大重连次数

logging:
  level:
    com.meetchance.abtest.starter.client.DefaultAbTestClient: debug
